server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  rabbitmq: #唯一需要说一下的，需要本地已经装了rabbitmq并启动
    host: paascloud-mq-rabbit
    port: 5672
    username: guest
    password: guest
  boot:
    admin:  #监控默认账号和密码
      username: admin
      password: admin

security:
  user: #界面默认账户和密码
    name: admin
    password: admin

info:
  软件著作权: paascloud快速搭建企业级分布式微服务平台
  著作登记号: 2018SR320076
  关于我们: http://paascloud.net